django/api/urls.py
from django.conf.urls import url
from api import views as api_views
from rest_framework.authtoken import views


urlpatterns = [
    url(r'^decks/$', api_views.decks_list, name='decks-list'),
    url(r'^decks/(?P<deck_id>[0-9]+)/$', api_views.deck_details, name='deck-details'),
    url(r'^decks/(?P<deck_id>[0-9]+)/cards/$', api_views.cards_list, name='cards-list'),
    url(r'^decks/(?P<deck_id>[0-9]+)/cards/(?P<card_id>[0-9]+)/$',
        api_views.card_details, name='card-details'),
    url(r'^decks/(?P<deck_id>[0-9]+)/cards/(?P<card_id>[0-9]+)/ratings/$',
        api_views.card_ratings, name='card-ratings'),

]

urlpatterns += [
            url(r'^api-token-auth/', views.obtain_auth_token, name='get-token')
            ]

django/config/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from flashcardgui import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.home),
    url(r'^flashcard/api/v1/', include('api.urls')),
    url(r'^flashcard/', include('flashcardgui.urls')),
    url(r'^accounts/registration/', include('registration.backends.hmac.urls')),
    url(r'^accounts/', include('django.contrib.auth.urls')),
]

django/flashcardgui/urls.py
from django.conf.urls import url
from flashcardgui import views


urlpatterns = [
    url('^$', views.home, name='home'),
    url('^about/$', views.about, name='about'),
    url('^profile/$', views.profile, name='flashcardgui.views.profile'),
    url('^add/$', views.add, name='add-card'),
    url('^add/newdeck$', views.add_new, name='add-card-deck'),
    url('^add/batch', views.add_batch, name='add-card-batch'),
    url('^study/(?P<deck_id>[0-9]+)/$', views.study, name='study'),
    url('^study/random/$', views.study_random, name='study_random'),
    url('^study/(?P<deck_id>\w+)/get_cards/$', views.get_cards, name='get-cards'),
    url('^study/(?P<deck_id>\w+)/reset_deck/$', views.reset_deck, name='get-reset_deck'),
    url('^delete_deck/$', views.delete_deck, name='delete_deck'),
    url('^rename_deck/$', views.rename_deck, name='rename_deck'),

    url('^post_results/$', views.post_results, name='post_results'),

]

django/flashcardgui/forms.py
from django import forms

from api.models import Deck


class CardForm(forms.Form):
    deck = forms.CharField(label='Deck', max_length=100)
    question = forms.CharField(label='Front', widget=forms.Textarea)

    def __init__(self, user, *args, **kwargs):
        super(CardForm, self).__init__(*args, **kwargs)
        self.fields['deck'].required = False
        decks= Deck.objects.filter(owner=user)
        self.fields['deck'].choices = decks.values()

django/flashcardgui/views.py
from itertools import chain

from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.http import JsonResponse
from django.utils import timezone
from django.views.decorators.csrf import ensure_csrf_cookie
from os.path import basename, splitext

import random
import json
import logging

from api.models import Deck, Flashcard, UserDeck
from flashcardgui.decorators import superuser_only
from .forms import CardForm
import requests
from bs4 import BeautifulSoup
CARD_LIMIT = 5

from raven.contrib.django.models import client

logging.basicConfig()  # you need to initialize logging, otherwise you will not see anything from requests
logging.getLogger().setLevel(logging.DEBUG)
requests_log = logging.getLogger("requests.packages.urllib3")
requests_log.setLevel(logging.DEBUG)
requests_log.propagate = True


@login_required
def home(request):
    """
    App home page
    """
    if request.method == 'GET':
        decks = Deck.objects.all()
        context = {'user': request.user, 'decks': decks}
        return render(request, 'flashcardgui/index.html', context)


def profile(request):
    """
    ...
    """
    if request.method == 'GET':
        pass


def about(request):
    """
    ...
    """
    if request.method == 'GET':
        return render(request, 'flashcardgui/about.html')


@login_required
@superuser_only
def add_batch(request):
    if request.method == 'POST':
        form = CardForm(request.user, request.POST)
        if form.is_valid():
            deck_name = form.cleaned_data['deck']
            question = form.cleaned_data['question']
            answer = ""
            user = request.user
            questions=question.splitlines()
            for question in questions:
                Flashcard.objects.create_flashcard(user=user, question=question,
                                               answer=answer, deck_name=deck_name,)
            return HttpResponseRedirect(reverse('add-card'))
    else:
        form = CardForm(request.user)

    return render(request, 'flashcardgui/add_batch.html', {'form': form,})


@login_required
@superuser_only
def add_new(request):
   return add(request,True)


@login_required
@superuser_only
def add(request,new=None):
    """
    Add new flashcard
    """
    if request.method == 'POST':
        form = CardForm(request.user, request.POST)
        if form.is_valid():
            deck_name = form.cleaned_data['deck']
            question = form.cleaned_data['question']
            #answer = form.cleaned_data['answer']
            user = request.user
            Flashcard.objects.create_flashcard(user=user, question=question,
                                               answer="", deck_name=deck_name,)
            return HttpResponseRedirect(reverse('add-card'))
    else:
        form = CardForm(request.user)

    return render(request, 'flashcardgui/add.html', {'form': form,'add_new':new})



@login_required
@ensure_csrf_cookie
def study_random(request):
    return study(request,'random')

@login_required
@ensure_csrf_cookie
def study(request, deck_id):
    """
    Study cards page (JS driven)
    """
    if request.method == 'GET':
        return render(request, 'flashcardgui/study.html',{'deck_id':deck_id})


@login_required
@ensure_csrf_cookie
def get_cards(request, deck_id):
    """
    Get cards to study (ajax)
    """

    if request.method == 'GET':
        if deck_id == 'random':
            used_cards = Flashcard.objects.filter(usercard__owner=request.user,
                                                  usercard__next_due_date__lte=timezone.now())
            new_cards = Flashcard.objects.all().exclude(usercard__owner=request.user)

        else:


            used_cards = Flashcard.objects.filter(usercard__owner=request.user, deck=deck_id,
                                             usercard__next_due_date__lte=timezone.now())
            new_cards = Flashcard.objects.filter(deck__id=deck_id).exclude(usercard__owner=request.user)


        cards = list(chain(used_cards,new_cards))
        count = len(cards)
        data = {'count': count, 'cards': []}

        num = count if count < CARD_LIMIT else CARD_LIMIT
        if num:
            # generate list of random indexes
            idx = random.sample(range(count), num)
            for i in idx:
                card = cards[i]
                question = '<p>'+'</p><p>'.join(card.question.split('\r\n'))+'</p>'
                answers=[]
                page_count = 0
                if card.answer == '' or card.modified_at+timezone.timedelta(3)<timezone.now():
                    url = "http://tidsozluk.net/tr/Sözcük/Arama/%s?"%(card.question)
                    page = requests.get(url)
                    soup = BeautifulSoup(page.text, 'html.parser')

                    first_match=soup.find('h3',string=card.question.capitalize())
                    pagination = soup.find('ul', class_='pagination')
                    if pagination:
                        page_count = len(pagination.find_all('li'))

                    if not first_match and page_count>0:
                        for x in range(2,page_count):
                            new_url = url + 'p=' +str(x)
                            page = requests.get(new_url)
                            soup = BeautifulSoup(page.text, 'html.parser')

                            match = soup.find('h3', string=card.question.capitalize())
                            if match:
                                first_match = match
                                break

                    if first_match:
                        answers.append(first_match.parent.parent.attrs.get('href'))



                if answers:
                    page = requests.get("http://tidsozluk.net%s"%answers[0])
                    soup = BeautifulSoup(page.text, 'html.parser')
                    div = soup.find_all('div', class_='container')
                    for img in div[0].findAll('img'):
                        img['src'] = "http://tidsozluk.net%s" % img['src']

                    for img in div[0].findAll('source'):
                        img['src'] = "http://tidsozluk.net%s" % img['src']

                    for vid in div[0].findAll('i',class_='vid_modal'):
                        vid['data-target'] = "http://tidsozluk.net%s" % vid['data-target']

                    answer = str(div[0])
                    card.answer = answer
                    card.save()
                else:
                    answer = '<p>'+'</p><p>'.join(card.answer.split('\r\n'))+'</p>'
                data['cards'].append({'id': card.pk, 'question': question,
                                     'answer': answer,'deck_id':deck_id})

        return JsonResponse(data)
    else:
        data = json.loads(str(request.body, 'utf-8'))
        for res in data:
            card = Flashcard.objects.get(pk=res['id'])
            userdeck,created = UserDeck.objects.get_or_create(owner=request.user, card=card      )
            userdeck.save(rating=res['result'])
        return JsonResponse({'status': 'OK'})


@login_required
@superuser_only
def delete_deck(request):
    """
    Delete deck (ajax)
    """
    if request.method == 'POST':
        data = json.loads(str(request.body, 'utf-8'))
        if 'deck_id' in data:
            deck = Deck.objects.get(owner=request.user, pk=data['deck_id'])
            deck.delete()
            return JsonResponse({'status': 'OK'})

@superuser_only
@login_required
def rename_deck(request):
    """
    Rename deck (ajax)
    """
    if request.method == 'POST':
        data = json.loads(str(request.body, 'utf-8'))
        if 'deck_id' in data and 'name' in data:
            deck = Deck.objects.get(owner=request.user, pk=data['deck_id'])
            name = data['name']
            deck.name = name
            deck.save()
            return JsonResponse({'status': 'OK'})
@login_required
def post_results(request):
    if request.method == 'POST':
        data = json.loads(str(request.body, 'utf-8'))

@login_required
def reset_deck(request, deck_id):
    if request.method == 'POST':
        data = json.loads(str(request.body, 'utf-8'))
        if 'deck_id' in data:
            deck = Deck.objects.get(owner=request.user, pk=data['deck_id'])
            usercards=request.user.usercard.filter(card__deck=deck)
            usercards.delete()
            return JsonResponse({'status': 'OK'})

django/flashcardgui/templates/flashcardgui/about.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block title %}Flashcard About{% endblock %}
{% block content %}
It's Flashcard Application
{% endblock %}

django/flashcardgui/templates/flashcardgui/add.html
{% extends "base.html" %}

{% block title %}Flashcard Add{% endblock %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-sm-8 col-sm-offset-2">
                <form action="{% url 'add-card' %}" method="post">
                    {% csrf_token %}
                    {% if form.errors %}
                        <!-- Error messaging -->
                        <div id="errors">
                            <div class="inner">
                                <p>There were some errors in the information you entered. Please correct the
                                    following:</p>
                                {{ form.non_field_errors }}
                                <ul>
                                    {% for field in form %}
                                        {% if field.errors %}
                                            <li>{{ field.label }}: {{ field.errors|striptags }}</li>{% endif %}
                                    {% endfor %}
                                </ul>
                            </div>
                        </div>
                        <!-- /Error messaging -->
                    {% endif %}
                    {% if form.fields.deck.choices and add_new is None %}
                        <div class="form-group">
                            <label for="{{ form.fields.deck.id_for_label }}">Deck</label>
                            <select name="deck" id="id_deck" class="form-control">
                                {% for choice in form.fields.deck.choices %}
                                    <option value="{{ choice.name }}">{{ choice.name }}</option>
                                {% endfor %}
                            </select>
                        </div>
                    {% endif %}
                    {% if not form.fields.deck.choices or add_new %}
                        <div class="form-group ">
                            <label for="id_deck">Deck</label>
                            <input type="text" name="deck" id="id_deck" class="form-control">
                        </div>
                    {% endif %}
                    <div class="form-group">
                        <label for="id_question">Question</label>
                        <textarea class="form-control" rows=3
                                  id="id_question"
                                  name="question"></textarea>
                    </div>



                    <button type="submit" class="btn btn-default">Add</button>


                </form>
            </div>
        <div class="md-col-2"><a class="btn btn-success" href="{% url 'add-card-deck' %}"><i class="fa fa-files-o"></i>Add New Deck</a>
        <a class="btn btn-warning" href="{% url 'add-card-batch' %}"><i class="fa fa-files-o"></i>Add Batch Card</a> </div>
        </div>
    </div>


{% endblock %}
{% block javascript %}
    {% load static %}
    <script src="{% static "js/bootstrap-select.min.js" %}"></script>
    <link href="{% static "css/bootstrap-select.min.css" %}" rel="stylesheet">
    <script>

        $(function () {
            $('#id_deck').selectpicker({});
        });
    </script>

{% endblock %}

django/flashcardgui/templates/flashcardgui/add_batch.html
{% extends "base.html" %}

{% block title %}Flashcard Add{% endblock %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-sm-8 col-sm-offset-2">
                <form action="{% url 'add-card-batch' %}" method="post">
                    {% csrf_token %}
                    {% if form.errors %}
                        <!-- Error messaging -->
                        <div id="errors">
                            <div class="inner">
                                <p>There were some errors in the information you entered. Please correct the
                                    following:</p>
                                {{ form.non_field_errors }}
                                <ul>
                                    {% for field in form %}
                                        {% if field.errors %}
                                            <li>{{ field.label }}: {{ field.errors|striptags }}</li>{% endif %}
                                    {% endfor %}
                                </ul>
                            </div>
                        </div>
                        <!-- /Error messaging -->
                    {% endif %}

                        <div class="form-group ">
                            <label for="id_deck">Deck</label>
                            <input type="text" name="deck" id="id_deck" class="form-control">
                        </div>
                    <div class="form-group">
                        <label for="id_question">Questions</label> <small>New word, new line. Press ENTER for new line.</small>
                        <textarea class="form-control" rows=40
                                  id="id_question"
                                  name="question"></textarea>
                    </div>



                    <button type="submit" class="btn btn-default">Add</button>
                </form>
            </div>
        <div class="md-col-2"><a class="btn btn-success" href="{% url 'add-card-deck' %}"><i class="fa fa-plus"></i>Add New Deck</a> </div>
        </div>
    </div>


{% endblock %}
{% block javascript %}
    {% load static %}
    <script src="{% static "js/bootstrap-select.min.js" %}"></script>
    <link href="{% static "css/bootstrap-select.min.css" %}" rel="stylesheet">
    <script>

        $(function () {
            $('#id_deck').selectpicker({});
        });
    </script>

{% endblock %}

django/flashcardgui/templates/flashcardgui/index.html
{% extends "base.html" %}
{% load bootstrap3 %}
{% load app_tags %}
{% block title %}Flashcard Home{% endblock %}
{% block content %}
    <div class="container">
        <h1>Decks</h1>
        <div class="row">
            <div class=" bg-info col-sm-8 col-xs-7">
                <i class="fa fa-random"></i> <a href="{% url 'study_random' %}">Rastgele 50 Kelime</a>

            </div>

        </div>
        {% for deck in decks %}
            <div class="row deck-row">
                <div class="col-sm-8 col-xs-7">
                    <a id="deckname{{ deck.id }}" href="{% url "study" deck.id %}">{{ deck.name|upper }}</a>
                </div>
                <div class="col-sm-1 col-xs-1">
                    {% get_card_num deck %}
                </div>
                {% if user.is_superuser %}
                    <div class="col-sm-1 col-xs-1">
                        <div class="dropdown">
                            <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1"
                                    data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                                Action
                                <span class="caret"></span>
                            </button>
                            <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                                <li><a href="#" onclick="renameHandler(this, {{ deck.id }});">Rename</a></li>
                                <li><a href="#" onclick="deleteHandler(this, {{ deck.id }});">Delete</a></li>
                            </ul>
                        </div>
                    </div>
                {% endif %}

            </div>
        {% endfor %}
    </div>

{% endblock %}
{% block javascript %}
    {% load static %}
    <script src="{% static "flashcardgui/decks.js" %}"></script>
{% endblock %}

django/flashcardgui/templates/flashcardgui/study.html
{% extends "base.html" %}

{% block title %}Flashcard Home{% endblock %}
{% block content %}
    {% load static %}

        <link rel="stylesheet" href="{% static 'css/custom.css' %}">

    <div class="container">
        <div class="row">
            <div class="col-sm-1 col-xs-1" id="buttons">
                <a href="#" onclick="resetHandler(this, {{ deck_id }});" id="reset-button" class="btn btn-default">Reset Test</a>
            </div>
            <div class="col-sm-1 col-sm-offset-10 col-xs-1 col-xs-offset-10" id="status">
            </div>
        </div>

        <div class="row">
            <div class="col-sm-12 text-center">
                <div id="question" class="text-uppercase h2"></div>
                    <div id="countdown"><div id="bar" class="bar h3"></div></div>
                        <div class="row">
            <div class="col-sm-12 text-center" id="result-row">
            </div>
        </div>
                </div>

            </div>
        </div>
                <div id="answer"></div>
    <canvas id="chart" class="chartjs" width="undefined" height="undefined"></canvas>

<div class="modal"></div>



<div class="modal fade" id="videoModal" tabindex="-1" role="dialog" aria-labelledby="videoModal" aria-hidden="true" data-backdrop="false">
  <div class="modal-dialog" style="margin:10px auto;">
    <div class="modal-content">
      <div class="modal-body" style="padding-top:7px;">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>

        <div id="modal_title"></div>

		<video id="modal_video" class="vid" autoplay muted  preload="metadata">
			<source src="" />
		</video>


			<div id="playinVidCont">
				<!-- <div id="vid_status" class="vid_butts"></div> -->
				<div id="vid_bar" style="display:block;height:10px;background-color:#aaa;border:1px solid;"><div id="vid_bar_cur" style="display:block;height:100%;background-color:red;width:0px;"></div></div>

				<div id="vid_kontrolz">

					<div id="vid_curTime" class="vid_kontrolz_commonz" style="font-size:1.2em;font-weight:600;">00.00</div>
					<div id="vid_duration" class="vid_kontrolz_commonz" style="font-size:1.2em;font-weight:600;"></div>
					<div id="vid_progress" class="vid_kontrolz_commonz" ></div>
					<div class="vidPlayParmzCont">
					<div id="vid_playSpdz" class="vid_kontrolz_commonz" >
						<div id="vid_playXq" data-spd="0.25" class="vid_spdz pntr">X 0.25</div>
						<div id="vid_playXh" data-spd="0.50" class="vid_spdz pntr">X 0.50</div>
						<div id="vid_playX1" data-spd="1.00" class="vid_spdz pntr vid_spd_active">X 1.00</div>
					</div>

					<div id="vid_playPause" class="" style="display:inline-block;">
					<!-- play-circle pause-circle  circle-o-notch-->
						<i id="vid_playin" class="fa fa-pause-circle fa-lg fa-2x pntr" style="position:relative;top:2px;left:6px;" aria-hidden="true"></i>
						<!-- <i id="vid_loopin" class="fa fa-circle-o-notch fa-lg pntr" style="position:relative;top:0px;left:16px;" aria-hidden="true"></i> -->
						<i id="vid_loopin" class="fa fa-repeat fa-lg pntr" style="position:relative;top:0px;left:16px;" aria-hidden="true"></i>
					</div>
					</div>

				</div>

			</div>

      </div>
    </div>
  </div>
</div>



{% endblock %}

{% block javascript %}
    <script src="{% static "flashcardgui/study.js" %}"></script>
    <script src="{% static "flashcardgui/decks.js" %}"></script>


    <script>php_lang = "tr"</script>

    <script type="text/javascript">


    </script>
    <script src="http://tidsozluk.net/jsS/siteIncs_v3.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.1/Chart.bundle.min.js"></script>

{% endblock %}